### ISSUE TITLE
bool is now boolean

### ISSUE THREAD

**Issue by jasonmeisel** [jbaldwin/sugar.d.ts#2]
using this lib gives you this error:
error TS2095: Could not find symbol 'bool'.

https://typescript.codeplex.com/wikipage?title=Known%20breaking%20changes%20between%200.8%20and%200.9

**Comment by KhodeN** [comment]
https://github.com/borisyankov/DefinitelyTyped/blob/master/sugar/sugar.d.ts is correct

**Comment by KhodeN** [comment]
I think this repository isn't actual at all

**Comment by jbaldwin** [comment]
Yes, I've been meaning to delete it for a while since all of my individual repositories have been merged into DefnitelyTyped.
